apiVersion: apps/v1
kind: Deployment
metadata:
  name: endocode-app
  namespace: dev
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: endocode-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: endocode-app
    spec:
      containers:
      - image: europe-docker.pkg.dev/mcspocbdcc-ef6a/go-docker/endocode:latest
        imagePullPolicy: Always
        name: cont-endocode
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
#        command:  // to
#          - tail  // debug
#          - "-f"  // the container
#          - /dev/null  // just in case
      imagePullSecrets:
        - name: registrypullsecret
      restartPolicy: Always