apiVersion: v1
kind: Service
metadata:
  name: endocode-service
  namespace: dev
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: endocode-app